"use client";
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";
// import { Triangle } from "react-loader-spinner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-svw flex justify-center relative overflow-y-scroll overflow-x-hidden`}
      >
        <NextUIProvider>
          {/* <div className="h-[100svh] w-[100svw] flex justify-center items-center">
            <Triangle
              visible={true}
              height="100"
              width="100"
              color="#282D4D"
              ariaLabel="triangle-loading"
              wrapperStyle={{}}
              wrapperClass=""
            />
          </div> */}

          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
